use crate::event::KeyCode;

/// Translate an OpenHarmony `KEYCODE_*` value into miniquad's [`KeyCode`].
///
/// Keep entries ordered by numeric value from `Input_KeyCode`. Some values are
/// available only behind newer `ohos-input-sys` API feature flags, so this table
/// intentionally matches on raw integer codes instead of enum variants.
pub fn translate_keycode(keycode: i32) -> KeyCode {
    match keycode {
        1 => KeyCode::Home,     // KEYCODE_HOME
        2 => KeyCode::Back,     // KEYCODE_BACK
        2000 => KeyCode::Key0,  // KEYCODE_0
        2001 => KeyCode::Key1,  // KEYCODE_1
        2002 => KeyCode::Key2,  // KEYCODE_2
        2003 => KeyCode::Key3,  // KEYCODE_3
        2004 => KeyCode::Key4,  // KEYCODE_4
        2005 => KeyCode::Key5,  // KEYCODE_5
        2006 => KeyCode::Key6,  // KEYCODE_6
        2007 => KeyCode::Key7,  // KEYCODE_7
        2008 => KeyCode::Key8,  // KEYCODE_8
        2009 => KeyCode::Key9,  // KEYCODE_9
        2012 => KeyCode::Up,    // KEYCODE_DPAD_UP
        2013 => KeyCode::Down,  // KEYCODE_DPAD_DOWN
        2014 => KeyCode::Left,  // KEYCODE_DPAD_LEFT
        2015 => KeyCode::Right, // KEYCODE_DPAD_RIGHT
        2016 => KeyCode::Enter, // KEYCODE_DPAD_CENTER
        2017 => KeyCode::A,     // KEYCODE_A
        2018 => KeyCode::B,
        2019 => KeyCode::C,
        2020 => KeyCode::D,
        2021 => KeyCode::E,
        2022 => KeyCode::F,
        2023 => KeyCode::G,
        2024 => KeyCode::H,
        2025 => KeyCode::I,
        2026 => KeyCode::J,
        2027 => KeyCode::K,
        2028 => KeyCode::L,
        2029 => KeyCode::M,
        2030 => KeyCode::N,
        2031 => KeyCode::O,
        2032 => KeyCode::P,
        2033 => KeyCode::Q,
        2034 => KeyCode::R,
        2035 => KeyCode::S,
        2036 => KeyCode::T,
        2037 => KeyCode::U,
        2038 => KeyCode::V,
        2039 => KeyCode::W,
        2040 => KeyCode::X,
        2041 => KeyCode::Y,
        2042 => KeyCode::Z,            // KEYCODE_Z
        2043 => KeyCode::Comma,        // KEYCODE_COMMA
        2044 => KeyCode::Period,       // KEYCODE_PERIOD
        2045 => KeyCode::LeftAlt,      // KEYCODE_ALT_LEFT
        2046 => KeyCode::RightAlt,     // KEYCODE_ALT_RIGHT
        2047 => KeyCode::LeftShift,    // KEYCODE_SHIFT_LEFT
        2048 => KeyCode::RightShift,   // KEYCODE_SHIFT_RIGHT
        2049 => KeyCode::Tab,          // KEYCODE_TAB
        2050 => KeyCode::Space,        // KEYCODE_SPACE
        2054 => KeyCode::Enter,        // KEYCODE_ENTER
        2055 => KeyCode::Backspace,    // KEYCODE_DEL
        2056 => KeyCode::GraveAccent,  // KEYCODE_GRAVE
        2057 => KeyCode::Minus,        // KEYCODE_MINUS
        2058 => KeyCode::Equal,        // KEYCODE_EQUALS
        2059 => KeyCode::LeftBracket,  // KEYCODE_LEFT_BRACKET
        2060 => KeyCode::RightBracket, // KEYCODE_RIGHT_BRACKET
        2061 => KeyCode::Backslash,    // KEYCODE_BACKSLASH
        2062 => KeyCode::Semicolon,    // KEYCODE_SEMICOLON
        2063 => KeyCode::Apostrophe,   // KEYCODE_APOSTROPHE
        2064 => KeyCode::Slash,        // KEYCODE_SLASH
        2067 => KeyCode::Menu,         // KEYCODE_MENU
        2068 => KeyCode::PageUp,       // KEYCODE_PAGE_UP
        2069 => KeyCode::PageDown,     // KEYCODE_PAGE_DOWN
        2070 => KeyCode::Escape,       // KEYCODE_ESCAPE
        2071 => KeyCode::Delete,       // KEYCODE_FORWARD_DEL
        2072 => KeyCode::LeftControl,  // KEYCODE_CTRL_LEFT
        2073 => KeyCode::RightControl, // KEYCODE_CTRL_RIGHT
        2074 => KeyCode::CapsLock,     // KEYCODE_CAPS_LOCK
        2075 => KeyCode::ScrollLock,   // KEYCODE_SCROLL_LOCK
        2076 => KeyCode::LeftSuper,    // KEYCODE_META_LEFT
        2077 => KeyCode::RightSuper,   // KEYCODE_META_RIGHT
        2079 => KeyCode::PrintScreen,  // KEYCODE_SYSRQ
        2080 => KeyCode::Pause,        // KEYCODE_BREAK
        2081 => KeyCode::Home,         // KEYCODE_MOVE_HOME
        2082 => KeyCode::End,          // KEYCODE_MOVE_END
        2083 => KeyCode::Insert,       // KEYCODE_INSERT
        2090 => KeyCode::F1,           // KEYCODE_F1
        2091 => KeyCode::F2,
        2092 => KeyCode::F3,
        2093 => KeyCode::F4,
        2094 => KeyCode::F5,
        2095 => KeyCode::F6,
        2096 => KeyCode::F7,
        2097 => KeyCode::F8,
        2098 => KeyCode::F9,
        2099 => KeyCode::F10,
        2100 => KeyCode::F11,
        2101 => KeyCode::F12,     // KEYCODE_F12
        2102 => KeyCode::NumLock, // KEYCODE_NUM_LOCK
        2103 => KeyCode::Kp0,     // KEYCODE_NUMPAD_0
        2104 => KeyCode::Kp1,
        2105 => KeyCode::Kp2,
        2106 => KeyCode::Kp3,
        2107 => KeyCode::Kp4,
        2108 => KeyCode::Kp5,
        2109 => KeyCode::Kp6,
        2110 => KeyCode::Kp7,
        2111 => KeyCode::Kp8,
        2112 => KeyCode::Kp9,        // KEYCODE_NUMPAD_9
        2113 => KeyCode::KpDivide,   // KEYCODE_NUMPAD_DIVIDE
        2114 => KeyCode::KpMultiply, // KEYCODE_NUMPAD_MULTIPLY
        2115 => KeyCode::KpSubtract, // KEYCODE_NUMPAD_SUBTRACT
        2116 => KeyCode::KpAdd,      // KEYCODE_NUMPAD_ADD
        2117 => KeyCode::KpDecimal,  // KEYCODE_NUMPAD_DOT
        2119 => KeyCode::KpEnter,    // KEYCODE_NUMPAD_ENTER
        2120 => KeyCode::KpEqual,    // KEYCODE_NUMPAD_EQUALS
        2816 => KeyCode::F13,        // KEYCODE_F13
        2817 => KeyCode::F14,
        2818 => KeyCode::F15,
        2819 => KeyCode::F16,
        2820 => KeyCode::F17,
        2821 => KeyCode::F18,
        2822 => KeyCode::F19,
        2823 => KeyCode::F20,
        2824 => KeyCode::F21,
        2825 => KeyCode::F22,
        2826 => KeyCode::F23,
        2827 => KeyCode::F24, // KEYCODE_F24
        _ => KeyCode::Unknown,
    }
}
